language: android

android:
  components:
    - build-tools-20.0.0
    - android-L
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

script:
  ./gradlew build